analyze_request:
  description: >
    Analyze the following message and extract all transportation-related information:
    Message: {message}
    
    Extract:
    - Client name and ID
    - Contact phone
    - Service date and time
    - Pickup and drop-off locations
    - Number of passengers
    - Luggage/cargo information
    - Any special requirements
    
    Output the extracted information as structured JSON.
  expected_output: >
    JSON object with all extracted fields, using null for missing information
  agent: request_analyzer

validate_information:
  description: >
    Validate the extracted information: {extracted_data}
    
    Check for:
    1. All required fields are present
    2. Date/time formats are valid
    3. Locations are recognizable
    4. Phone number format is correct
    
    If information is missing, generate friendly questions in Spanish
    to ask for the missing details.
  expected_output: >
    Validation result with missing fields and suggested questions
  agent: information_validator
